.\"     Title: ltp
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "LTP" "1" "07/17/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ltp - preprocesses template files containing embedded Lua code
.SH "SYNOPSIS"
\fBltp\fR [\fIoptions\fR] \fItemplate_file\fR [\fIenv_file1\fR \fIenv_file2\fR \fI\&...\fR]
.sp
.SH "DESCRIPTION"
ltp is a general purpose text preprocessor intended for generative programming and template\-based document generation\. It processes a template file combined with zero or more environment files containing the data to be inserted into the template\. Expressions embedded in templates are evaluated as Lua code within an environment formed from the successive composition of all the environment files\.
.sp
The resulting document is written to standard output\. To write output to a specific file, you should use shell output redirection\.
.sp
.SH "OPTIONS"
.PP
\fB\-c\fR
.RS 4
Compiles template to Lua code\.
.RE
.PP
\fB\-C\fR
.RS 4
Compiles template to Lua code, omitting the function wrapper\.
.RE
.PP
\fB\-e\fR \fIcode\fR
.RS 4
Executes Lua code within the template execution environment immediately before executing the template\.
.RE
.PP
\fB\-g\fR
.RS 4
Merges global environment into rendering environment\.
.RE
.PP
\fB\-h,\-\-help\fR
.RS 4
Prints this help message\.
.RE
.PP
\fB\-I directory\fR
.RS 4
Adds a directory to the search path for require directives\.
.RE
.PP
\fB\-n\fR \fI#\fR
.RS 4
Performs successive expansions of template output, treating the output as a new template, for a total of
\fI#\fR
passes\. This allows the use of embedded expressions\. By default, only a single pass (# = 1) is made (i\.e\., only the original template is evaluated)\. A value of 0 may be specified to cause as many passes to be performed as necessary so that no embedded expressions remain in the output\.
.RE
.PP
\fB\-t\fR \fIstart_lua_token\fR \fIend_lua_token\fR
.RS 4
Specifies the start and end tokens that demarcate embedded Lua code\. The defaults are
\fI<?lua\fR
and
\fI?>\fR\.
.RE
.PP
\fB\-v,\-\-version\fR
.RS 4
Prints version information\.
.RE
.SH "EXAMPLES"
This section is incomplete and will contain explanations and examples for writing template and environment files\. For now, the most important items to understand are that you can access the ltp\.import and ltp\.merge_table functions from within a template or environment file\.
.sp
.SS "ltp\.import(module_name, environment)"
Templates may be compiled for inclusion by other templates via the ltp\.import function\. For example, you may have a header template that is imported by a document template\.
.PP
\fBExample\ 1.\ head.ltp\fR
.sp
.RS 4
.nf
<head>
  <title><?lua= page\.title ?></title>
</head>
.fi
.RE
This template would be compiled with:
.sp
.sp
.RS 4
.nf
ltp \-c head\.ltp > head\.lua
.fi
.RE
This command compiles the template to a lua function that accepts a single argument called \fIoutput\fR\. Import the template with:
.PP
\fBExample\ 2.\ document.ltp\fR
.sp
.RS 4
.nf
<html xmlns="http://www\.w3\.org/1999/xhtml" xml:lang="en" lang="en">
<?lua ltp\.import(\'head\', getfenv())(output) ?>
<body>
\.\.\.
</body>
.fi
.RE
The \fIoutput\fR variable is an implicit global table available inside of templates that stores rendered content\. The use of getfenv() ensures that page\.title is availble to head\.ltp\.
.sp
You can also create a library of functions by compiling with the \fI\-C\fR option and returning a table of functions from the template library\. For example, instead of a header template, you could write a header function:
.PP
\fBExample\ 3.\ head.ltp\fR
.sp
.RS 4
.nf
<?lua local function head(output, title) ?>
<head>
  <title><?lua= title ?></title>
</head>
<?lua end
  return { head = head }
 ?>
.fi
.RE
.sp
.RS 4
.nf
ltp \-C head\.ltp > head\.lua
.fi
.RE
.PP
\fBExample\ 4.\ document.ltp\fR
.sp
.RS 4
.nf
<html xmlns="http://www\.w3\.org/1999/xhtml" xml:lang="en" lang="en">
<?lua
  local head = require(\'head\')\.head
  head(output, page\.title)
 ?>
<body>
\.\.\.
</body>
.fi
.RE
.SS "ltp\.merge_table(t1, t2)"
Even though \fBltp\fR merges multiple environment files specified on the command line, there are times when a self\-contained template or environment file needs to import and merge data from another source\. You can use the ltp\.mergetable function to do this\. For example, let\'s say you have an environment file that uses color data from another file:
.PP
\fBExample\ 5.\ style.lua\fR
.sp
.RS 4
.nf
local Color = require(\'colors\.lua\')

local style =
[[
<style type="text/css">
html {
  background\-color: <?lua= Color\.Black ?>;
  color: <?lua= Color\.White ?>;
}
<style>
]]

return ltp\.merge_table({style = style}, {Color = Color})
.fi
.RE
Environment files must return a table whose fields are merged into the global environment when executing a template\. ltp\.merge_table merges the second argument into the first argument and returns the first argument after merging\. Of course, the above example didn\'t require the use of ltp\.merge_table\. The environment file could have returned a single table:
.sp
.sp
.RS 4
.nf
return {style = style, Color = Color }
.fi
.RE
However, when two tables share element names and one should override the other, you must use ltp\.merge_table\.
.sp
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Indicates the program terminated without producing any errors\.
.RE
.PP
\fB1\fR
.RS 4
Indicates the program terminated after encountering an error\.
.RE
.SH "BUGS"
Report bugs to software at savarese\.com\.
.sp
Currently, it is not possible to nest \fI<?lua \&... ?>\fR within Lua code in a template file\. A workaround is to precompile the template, using different tokens for the template code and the nested data\. For example, you can write the following:
.sp
.sp
.RS 4
.nf
<?ltp local name = [[<?lua= lastname ?>, <?lua= firstname ?>]] ltp?>
.fi
.RE
Then you can precompile the template with:
.sp
.sp
.RS 4
.nf
ltp \-c \-n 1 \-t "<?ltp" "ltp?>" \.\.\.
.fi
.RE
Finally, you can use the compiled template via require or ltp\.import calls\.
.sp
.SH "AUTHOR"
Written by Daniel F\. Savarese, Savarese Software Research Corporation\.
.sp
.SH "COPYRIGHT"
Copyright 2007\-2008 Savarese Software Research Corporation\.
.sp
.SH "LICENSE"
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at
.sp
.sp
.RS 4
.nf
http://www\.savarese\.org/software/ApacheLicense\-2\.0
.fi
.RE
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\. See the License for the specific language governing permissions and limitations under the License\.
.sp
